Personal:
  $FIRST$: Samer
  $LAST$: El-Abd
  $HEADLINE$: PhD Candidate at the University of Virginia Deptartment of Astronomy
  $BIO$: I'm a really cool dude with a really cool beard
  $EMAIL$: sje2tu@virginia.edu
Primary Author Publications:
  - $TITLE$: Example Primary Paper
    $URL$: https://alecbonham.com/
    $ICON$: fa-book
    $BLURB$: A really cool website by my friend Alec
Coauthor Publications:
  - $TITLE$: Example Coauthor Paper
    $URL$: http://joshferey.com/
    $ICON$: fa-book
    $BLURB$: A really cool website by my friend Josh
